apiVersion: v2
appVersion: "0.11.0"
description: NVR With Realtime Object Detection for IP Cameras
name: frigate
version: 7.0.1
keywords:
  - tensorflow
  - coral
  - ml
home: https://github.com/zad80/helm/tree/master/charts/frigate
icon: https://github.com/blakeblackshear/frigate/blob/master/docs/static/img/frigate.png
sources:
  - https://github.com/blakeblackshear/frigate
maintainers:
  - name: zad
    email: zad80@gmail.com
